x-common:
  panel:
    &panel-environment
    APP_URL: "https://localhost"
    APP_DEBUG: "false"
    ADMIN_EMAIL: "USEYOUROWNEMAILHERE@example.com"

    APP_ENVIRONMENT_ONLY: "false"
    APP_ENV: "production"
    SESSION_DRIVER: "file"

  mail:
    &mail-environment
    MAIL_DRIVER: "log"
    # MAIL_HOST: ""
    # MAIL_PORT: ""
    # MAIL_FROM: ""
    # MAIL_USERNAME: ""
    # MAIL_PASSWORD: ""
    # MAIL_ENCRYPTION: ""

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:
  panel:
    image: panel
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/pelican-data
      - .:/srv
    environment:
      <<: [*panel-environment, *mail-environment]
    working_dir: /srv

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
      - .:/srv
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env.docker
    environment:
      <<: [ *panel-environment, *mail-environment ]
      XDG_DATA_HOME: /pelican-data
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

volumes:
  pelican-data:
  caddy-data:
  caddy-config:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
